#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod -R o-rwx "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R $app:www-data "$install_dir"
#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Configuring NGINX web server..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Create a dedicated PHP-FPM config
ynh_config_add_phpfpm

#=================================================
# MODIFY A CONFIG FILE
#=================================================

ynh_config_add --template="database.php" --destination="$install_dir/app/Config/database.php"

#=================================================
# MODIFY FIRST.CTP

#=================================================

ynh_replace --match="app/webroot/" --replace="" --file="$install_dir/app/View/Install/first.ctp"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
