#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# CHECK VERSION
#=================================================

upgrade_type=$(ynh_check_app_version_changed)

#=================================================
# STANDARD UPGRADE STEPS
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

if [ "$upgrade_type" == "UPGRADE_APP" ]
then
	ynh_script_progression --message="Upgrading source files..." --weight=7

	# Download, check integrity, uncompress and patch the source from app.src
	ynh_setup_source --dest_dir="$install_dir" --keep="app/Config/database.php"
fi

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Upgrading NGINX web server configuration..." --weight=2

# Create a dedicated NGINX config
ynh_add_nginx_config

# Create a dedicated PHP-FPM config
ynh_add_fpm_config --usage=low --footprint=low

#=================================================
# MODIFY A CONFIG FILE
#=================================================
#ynh_script_progression --message="Updating a configuration file..."--weight=1

#ynh_add_config --template="../conf/database.php" --destination="$install_dir/app/Config/database.php"

#=================================================
# MODIFY FIRST.CTP 
#=================================================

ynh_replace_string --match_string="app/webroot/" --replace_string="" --target_file="$install_dir/app/View/Install/first.ctp"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of MineWeb completed" --last
